# Generated by Django 5.1.7 on 2025-04-17 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_tests', '0002_clinicalsession_delete_testsession'),
        ('final_prediction', '0003_alter_finalprediction_user_alter_userprediction_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField()),
                ('options', models.JSONField()),
                ('is_open_ended', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('scoring_rules', models.TextField()),
                ('is_placeholder', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='clinicalsession',
            old_name='completed',
            new_name='is_complete',
        ),
        migrations.RenameField(
            model_name='clinicalsession',
            old_name='timestamp',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='clinicalsession',
            name='followup_counts',
        ),
        migrations.RemoveField(
            model_name='clinicalsession',
            name='gemini_response_log',
        ),
        migrations.RemoveField(
            model_name='clinicalsession',
            name='score',
        ),
        migrations.RemoveField(
            model_name='clinicalsession',
            name='test_name',
        ),
        migrations.AddField(
            model_name='clinicalsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinicalsession',
            name='prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='final_prediction.finalprediction'),
        ),
        migrations.AddField(
            model_name='clinicalsession',
            name='total_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.JSONField(blank=True, null=True)),
                ('open_ended_answer', models.TextField(blank=True, null=True)),
                ('follow_up_questions', models.JSONField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinical_tests.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='clinical_tests.clinicalsession')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='clinical_tests.test'),
        ),
        migrations.AddField(
            model_name='clinicalsession',
            name='test',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='clinical_tests.test',
                null=True,  # Changed to allow null for existing rows
            ),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('test', 'order')},
        ),
    ]