# Generated by Django 5.1.7 on 2025-04-18 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinical_tests', '0003_question_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicalsession',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinical_tests.test'),
            preserve_default=False,
        ),
    ]
