# Generated by Django 5.1.7 on 2025-04-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresponse',
            name='is_followup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userresponse',
            name='question',
            field=models.TextField(),
        ),
    ]
