# Generated by Django 5.1.7 on 2025-04-16 10:20

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_detail', '0002_userresponse_is_followup_alter_userresponse_question'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userresponse',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='userresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userresponse',
            name='parent_response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='user_detail.userresponse'),
        ),
    ]
