# Generated by Django 5.1.7 on 2025-04-17 12:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authuser', '0002_alter_phoneotp_email_alter_phoneotp_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='name',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='password',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='username',
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='user',
            field=models.ForeignKey(
                null=True,  # Temporary nullability
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]