# Generated by Django 5.1.7 on 2025-04-19 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='plot_keywords',
            new_name='keywords',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='genre',
            new_name='mood',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='mood_tags',
        ),
        migrations.RemoveField(
            model_name='song',
            name='mood_tags',
        ),
        migrations.RemoveField(
            model_name='song',
            name='tempo',
        ),
        migrations.RemoveField(
            model_name='song',
            name='valence',
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='mood',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='features',
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='language',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
